### PR TITLE
Add support for podman

### PR DESCRIPTION
**Pull request by nr23730**
This PR adds support for Podman and probably other OCI compatible container engines.

Changes include:
- Add `docker.io/` prefix to all images that are stored on DockerHub (does not break compatibility with Docker!)
- Rebuild of ensembl-rest image to avoid uids >65536
  - this is useful for rootless execution and probably also helps if docker is executed in rootless mode

### CODE REVIEW

**Review by BoehmDo — APPROVED** [review]
Hi, @nr23730. Thank you for this addition. I was successful in building and deploying the project using podman-compose as well as docker-compose, so lgtm! However, podman-compose still struggled with the uids used in the ensembl-rest image and required the "ignore_chown_errors" flag to be set in the storage.conf file in order to successfully pull all images. If that remains consistent behaviour it might be worth adding to the readme.

**Comment by nr23730** [comment]
Thanks alot! I updated to ensembl-rest image to vep 110 and fixed the ownership issues. 
So now it should *really* work out-of-the-box.

**Comment by BoehmDo** [comment]
Thanks for the update! Have you pushed the new image 110 to dockerhub already? For me the build fails with manifest unknown for the ensembl-rest image and the last tag i can find is 109.

**Comment by nr23730** [comment]
Looks like the upload failed. I'll upload again.

**Pull request merged**
